version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A src.tasks.celeryconfig:app worker --loglevel=info
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A src.tasks.celeryconfig:app beat --loglevel=info
    depends_on:
      - redis
